sudo: required

language: go

go:
- 1.8

env:
  global:
  - secure: G06C5ygP0RM7v3oVPd7QQsOQAlj1vAmJlgVERVsxFEiqk05vRvmSNEVX50pg3EMNxzUpHIkq0y2QZKj918UOIsdiTP7WRjcv9ONqf5jKvRiMHB6E4NY/zXxWg5GFqyl59IqufXOv12M2yX7w6L5en63Pk72cNUIcAZvSueUJpLd4t88ViaxN6gijHP9vwabuhfQSRuQgtW7ayHINEBC3TQxm+Hw8qLMdDfZ5OhWZ35jvLyNIAKan1YkcgdmSpMs5PP1PyvYsPcWkcolAh+3hwDa74dvrCZ6i5g2LNZUw6TI60vpjPlZ4HH7UFGykFKKuEdiMU1CaWj2Glg7k2vSL64hnmjLcNbEZSkrNv/C43vxE5bITr352lY7+bMlChw+XGg3coz9UxGGdSqGfcN9weBmV1fGwD1yJuzGi8UM4o7LivfzFnWPakXAkrTW61XZ3GaRwCa5GolxG4DCcQI8mVPnVPv1a0/BF35oJOARYWtevkr4khq78dKRC4qloHbcXUiwk2eZpMHcOeKWu8GT4Kr7RJBA0TkH7swrSHlafIHH28qmHj5XxEbv9yFuViMWEgaoZk4yZ94LGzMWiLSlE6lQ11AqtL1xfYkPpzfCs12A6PYcwW73OHS0gUu+5ed+xtKG/4GQVo9bX+D0DxRgYlVl3ZJBTGdwbNpO6L7xxPNM=
  - secure: jzA0OYIWGrZe6MW+nhXfaxRS+JX+nY0lLupdwM1DXIbY4oZyrn3gQCQ17cOvPB7S7jnB5q6tcO7njXsVogi4MyV/HWbuWvJPRY2gOxYPB7dfQ2TPq192MbgkijK27LRtKjTizzRkXtBWV2uUw0LN8tU6BcdW4HyukcoRlVz8gBWIw6qaL9exvXtrZ7IJZ9JBe07y/rJOIoedh5wV/zVkNoB8AqVKbYwL7Dyf7UkCB92hKzqJItQ1VtJa/q4GmvXomM5ENz4i+swPz+4/7hGPH3NjocNGiEpCV+9TilrD6OQvCt4juEBO2/NzejWgm1memHDMiyIOb8Uf3D40g/ZeBzEXBD40MGJNpkAxVrN59uWh22sNZLNfgAIV8KHaSJfpnUt4RTYHbM7p9guWVPrgRFDLcCBkng+o+FIkTVTBnbtR98RTcgumieD40Yu4fnnd+VDuIYVF48uqq19r49k+Xu3KeIv1v4O3K1GQdOk3M2TyaTob1RC0NcQnY1hUUnNy3cmZAPawFd8nxemVvLDamwyEQIVZCqMx4Rz7W9OKeInyAzZnKM7BEWyXKofVA3sUgTKj0anXmomntxhrwnhdB8W2YegUxkiwMPXuSQUp702xStLb7Fua+d1G75H56Yq5G1kJDs2vBQ7nbBaA4jYYH6hrs6zldUn9X1lG56wFW7Q=

install:
- make install_ci

script:
- make test_ci
- goveralls -coverprofile=cover.out -service=travis-ci

after_success:
- bash ./travis/build-docker-images.sh