sudo: required

language: go

go:
- 1.8

env:
  global:
  - secure: FrA1RCWdpXI1u6EFUuij4mt/4KVXL1CPwtuGkRm8sPt3dK9KFVteBPusFYU5G3DZxdRGX8026WH8W+ppFdFS6pVc8c9IXMWkP+te5dCAzzd+PA4QhndNp1+5TnSMJTtDmTU39oe9306r/2a2I8ThsL4GaNB7BcGW+nerJkwSjNxCNtsnJ2As7UXSc904r6snADLX2l8xH8SeRjhbyUwcjmK5W50JRRlfG8tXJkRuTwYS5Fq7EhOs3vRbKI6h2SPCd4YreC5tIwe9DArAyLScjUV/n96469yB3o+iJ1CUT9evNjgUwvCuQ36iqfp+EvwGh+FQY5aDtlb6dn9S//3lziYUb4SNsXpATnoCdK6l+ZTZult3DSHPicoE1/+/EWWl2ZQRVl5vnVrX6NLFBcQVytLm/xlkjh4whCi+v0WWNC8MtwtEyHbY+gOW4lRsO0WZxRcx3xxj/6H/9/dydjknmXtRCemmKGB+Y2LmW0crAIWyD12bCe+3+Xel0gDlDZnPWOGDC3dqfzDWiX3MRz1jk/FImOpISHrCxKk0r2OakxTQd7hwuzgD1FYzfdVhCr7bkgEDb55qhwhfQ2lCYgYyNPkiBS8az3E4VppZbee9IOjN74G2XYEJ1hvHkd6TomsSOyeZS5P6SCXV6iDep86gg6FmbSW9zsOxYl0uneAi8ng=
  - secure: mvrbXPrMD69cfn+6YV3mrzjGS/r3IcTujuGBX7PJSxaLs50ao+/xuYkLWka2XN2dmKAGNAyA4sjCm3mAjw+PB2tSGeiwK6qyqlKNAgSC7ehG2XVg4a/e++uRt9nHapVSADf1RibaJjNdkKnLergmzKII5vLyq9p3QGRwiHm49DfWZzZ9y227ZKT/v0+satCdZLb3Zf8YBgyQCn9pT1erFEivlcw9yov7zM3ZU+GYiSQXLCNF52/zvGyxRwEy5MIz2iYUy1a7LB2dHz5yB+902U1OWaYWl5lQUh9HWrh0PfgEzYbzhFPsW+ANsI5kHD0aamMBt3eWUj2GqridbPfcuWV5t0IcBQ5ky8hgQ+1zG9gJp060BMzDm/5RHaGPLE3bpztIpUw7vM/U9W3icUCQhggrMaGZUBZp/hIFOgOrEXWbVdTDvspu9i1CL3CGRc8LCyTO2ie8sSd7OKEFtY6XeLO0c7r2+nBHMFzlM6Am1YNy6Ugjx4sxXWuGw/tlvtnZecUUFpeNQYzBa38KmQSXuo9Cu0UiLkjWxpKHndbHBc3uqEL+myYx2XlP1f55xEUN//40Et80XQk6tLqLo/rcE8+ct851xcLqLtYnJogAJqEljKZQgmNhykWGBNsXM1qw4zIm/faYQW+Z6gsghTXBWGMTA9P+20OlUMp/YcnRot4=
  - secure: r8TlBGTU8QvQsI2EKyUdN2ShsmvTXYGUtpIRp1haVb4Xinozv3+eLW70Pyf6ZNTNso9DrkEqjhy9abddebOEA343qtu6pXI9Lb+2kvJ8x8yrD1kXf/E7zH0LuOOyNXS3ll4XW05rmQvzL5t8Ag/ZDi5xumFaKE37dOdVuu/hlJ9ATW/MuncONPv3PiTQoudDOvC59P2+Tk28Uk5uCthKxvpXBde4Ex9nXIyEeGHgS/rw37a7I+8EIuRWESUFwE4xdTO4+RiJ1rpTJGiheEmDKp7QBrXOhxknS/zQbAIrPWa4rCuqbdaJzbJgpPU3ZQvv68UTNIuMSJezLfFbf0vkZy9snmt1fMK1OKSaL+m5kCdSH5VRl3YPXnLB6KETxc8+2qm0+Ix8S3tfstcj8dXZEUmB1g1pTNkuRR/zArSFcWJulMItSCd0GUkEJ3bB3gMrw/i7gAmxQ3mUqrD2hkmOMiwRYDyDUO9AxgIUhUBv4r15lULJl1dXeEhof1woPOkHB2WHxxqbkpC6CLKhCbbxU4TETbwCJGEcPylpjV7PrgKX5k1cn1MeA7pCzkN774MGWV43I8fbhHB89Czi00gMRQG07HUq3DTIDcNEG5hDIS5fRi0xDs8cJAfW+mXz3LbJCtv0NGMcKEtGJ8qlJ3ct1uYhddFLOA84w2o0FyQGR/4=


install:
- make install_ci

script:
- make test_ci
- goveralls -coverprofile=cover.out -service=travis-ci

after_success:
- bash ./travis/build-docker-images.sh
