# This is an example configuration file for Kanali.
# Note that all of the following options can be specified via cli flags.
# In addtion, JSON and YAML formats can also be used.

[tracing]
jaeger_server_url = "jaeger-agent.kube-system.svc.cluster.local"
jaeger_agent_url = "jaeger-agent.kube-system.svc.cluster.local"

[analytics]
influx_addr = "http://kanali-influxdb.default.svc.cluster.local:8086"
influx_db = "kanali"
influx_username = ""
influx_password = ""

[plugins]
location = "/"

[plugins.apiKey]
decryption_key_file = "/etc/kanali/key.pem"
header_key = "apikey"

[tls]
cert_file = "/etc/pki/tls.crt"
key_file = "/etc/pki/tls.key"
ca_file = ""

[server]
port = 8443
bind_address = "0.0.0.0"
peer_udp_port = 10001
proxy_protocol = false

[process]
log_level = "info"

[proxy]
enable_cluster_ip = true
enable_mock_responses = true
upstream_timeout = "0h0m10s"
header_mask_value = "ommitted"
tls_common_name_validation = false
mask_header_keys = [
  "apikey"
]

[proxy.default_header_values]
x-canary-deployment = "stable"