[metadata]
name = "github.com/northwesternmutual/kanali"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "v1.3.8"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "master"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.2.11"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "89b2a556a65053a90552eaed26f810df4a266367" # release-1.8

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "9d38e20d609d27e00d4ec18f7b9db67105a2bde0" # release-1.8

[[constraint]]
  name = "k8s.io/client-go"
  revision = "afb4606c45bae77c4dc2c15291d4d7d6d792196c" # release-5.0

[[constraint]]
  name = "k8s.io/api"
  revision = "cadaf100c0a3dd6b254f320d6d651df079ec8e0a" # release-1.8

# the following constraint must be updated
# once this PR has been merged:
# https://github.com/uber-go/zap/pull/538
[[constraint]]
  name = "go.uber.org/zap"
  branch = "grpclog-v2"
  source = "github.com/frankgreco/zap"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"

# the following constraint is a temporary hack until
# the following issue is resolved:
# https://github.com/golang/dep/issues/1457
[[constraint]]
  name = "github.com/apache/thrift"
  revision = "b2a4d4ae21c789b689dd162deb819665567f481c"
