---

plugins:
- name: apiKey
  source: github.com/northwesternmutual/kanali-plugin-apikey
  versions:
  - name: v2.0.0
    default: true
    version: v2.0.0
  - name: abc123
    default: false
    revision: abc123
  - name: master
    default: false
    branch: master