---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kanali
  labels:
    app: kanali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kanali-role
subjects:
- kind: ServiceAccount
  name: kanali
  namespace: default