---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kanali
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: kanali
  template:
    metadata:
      labels:
        k8s-app: kanali
    spec:
      serviceAccountName: kanali
      containers:
      - name: kanali
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/kanali:{{.Values.dockerImageTag}}
        args:
        - start
        - --kanali-port=8443
        - --bind-address=0.0.0.0
        - --log-level=info
        - --enable-mock
        - --enable-cluster-ip
        - --tls-cert-file=/etc/pki/tls.crt
        - --tls-private-key-file=/etc/pki/tls.key
        - --decryption-key-file=/etc/kanali/key.pem
        - --plugins-location=/
        - --disable-tls-cn-validation
        - --influxdb-addr=http://kanali-influxdb.default.svc.cluster.local:8086
        - --influxdb-database=kanali
        - --jaeger-sampler-server-url=jaeger-agent.kube-system.svc.cluster.local
        - --jaeger-agent-url=jaeger-agent.kube-system.svc.cluster.local
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "50m"
        ports:
        - containerPort: 8443
        - containerPort: 8080
        volumeMounts:
        - name: pki
          mountPath: /etc/pki
        - name: decrypt-key
          mountPath: /etc/kanali
      volumes:
      - name: pki
        secret:
          secretName: {{.Values.tlsSecretName}}
      - name: decrypt-key
        secret:
          secretName: {{.Values.decryptKeySecretName}}