---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kanali
rules:
  - apiGroups: ["kanali.io"]
    resources: ["apikeies", "apiproxies", "apikeybindings", "mocktargets"]
    verbs: ["watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kanali
  labels:
    app: kanali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kanali
subjects:
- kind: ServiceAccount
  name: kanali
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kanali
  name: kanali
  namespace: default