---

apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: application

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-six
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: example-six
  template:
    metadata:
      labels:
        k8s-app: example-six
    spec:
      containers:
      - name: example-six
        imagePullPolicy: Always
        image: fbgrecojr/helloworld:golang
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: example-six
  namespace: application
spec:
  selector:
    k8s-app: example-six
  ports:
  - name: http
    port: 8080
  type: ClusterIP

---

apiVersion: kanali.io/v1
kind: ApiProxy
metadata:
  name: example-six
  namespace: application
spec:
  source:
    path: /api/v1/example-six
  target:
    path: /
    backend:
      service:
        port: 8080
        name: example-six
  plugins:
  - name: apiKey
    version: v1.2.0
    config:
      bindingName: example-six

---

apiVersion: kanali.io/v2
kind: ApiKey
metadata:
  name: janes-apikey
  namespace: application
spec:
  revisions:
  - data: rsa_encrypted_data
    status: active
    lastUsed: "Mon May 4 14:32:59 CDT 2018"
  - data: rsa_encrypted_data
    status: inactive
    lastUsed: "Mon May 4 14:32:59 CDT 2018"

---

apiVersion: kanali.io/v1
kind: ApiKeyBinding
metadata:
  name: example-six
  namespace: application
spec:
  keys:
  - name: janes-apikey
    defaultRule:
      granular:
        verbs:
        - GET