---

apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: application

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-two
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: example-two
  template:
    metadata:
      labels:
        k8s-app: example-two
    spec:
      containers:
      - name: example-two
        imagePullPolicy: Always
        image: fbgrecojr/helloworld:golang
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: example-two
  namespace: application
  labels:
    app: example-two
    release: production
spec:
  selector:
    k8s-app: example-two
  ports:
  - name: http
    port: 8080
  type: ClusterIP

---

apiVersion: "kanali.io/v1"
kind: ApiProxy
metadata:
  name: example-two
  namespace: application
spec:
  path: /api/v1/example-two
  target: /
  service:
    port: 8080
    labels:
    - name: app
      value: example-two
    - name: release
      header: deployment
