---

apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: application

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-one
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: example-one
  template:
    metadata:
      labels:
        k8s-app: example-one
    spec:
      containers:
      - name: example-one
        imagePullPolicy: Always
        image: fbgrecojr/helloworld:node-opentracing
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: example-one
  namespace: application
spec:
  selector:
    k8s-app: example-one
  ports:
  - name: http
    port: 8080
  type: ClusterIP

---

apiVersion: kanali.io/v1
kind: ApiProxy
metadata:
  name: example-one
  namespace: application
spec:
  path: /api/v1/example-one
  target: /
  service:
    port: 8080
    name: example-one
