---

apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: application

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: example-three
  namespace: application
data:
  response: |-
    [{
        "route": "/health",
        "code": 200,
        "method": "GET",
        "body": {
            "msg": "all systems are up and running"
        }
    },
    {
        "route": "/accounts",
        "code": 200,
        "method": "GET",
        "body": [{
            "id": "1",
            "balance": "$500.00"
        },
        {
            "id": "2",
            "balance": "$1000.00"
        }]
    }]

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example-three
  name: example-three
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: example-three
  template:
    metadata:
      labels:
        k8s-app: example-three
    spec:
      containers:
      - name: example-three
        imagePullPolicy: Always
        image: fbgrecojr/helloworld:golang
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: example-three
  namespace: application
spec:
  selector:
    k8s-app: example-three
  ports:
  - name: http
    port: 8080
  type: ClusterIP

---

apiVersion: "kanali.io/v1"
kind: ApiProxy
metadata:
  name: example-three
  namespace: application
spec:
  path: /api/v1/example-three
  target: /
  mock:
    configMapName: example-three
  service:
    port: 8080
    name: example-three
