---

apiVersion: v1
kind: Service
metadata:
  name: etcd-grpc-proxy
  namespace: default
spec:
  selector:
    app: etcd
  ports:
  - port: 23790
    name: etcd
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd-cluster
        imagePullPolicy: IfNotPresent
        image: quay.io/coreos/etcd:v3.3
        command:
        - etcd
        - --listen-client-urls=http://localhost:2379
        - --advertise-client-urls=http://localhost:2379
        ports:
        - containerPort: 2379
      - name: etcd-grpc-proxy
        imagePullPolicy: IfNotPresent
        image: quay.io/coreos/etcd:v3.3
        command:
        - etcd
        - grpc-proxy
        - start
        - --endpoints=127.0.0.1:2379
        - --listen-addr=0.0.0.0:23790
        - --advertise-client-url=192.168.99.100:31747
        ports:
        - containerPort: 23790
