---

dependencies:
- name: influxdb
  version: 0.6.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - influxdb
- name: grafana
  version: 0.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - grafana
- name: jaeger
  version: 0.2.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  tags:
  - jaeger
- name: etcd
  version: 0.3.5
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  tags:
  - etcd